
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import "@/styles/globals.css";

import { DBContextProvider } from "@/context/DBContextProvider";
import { SectionControllerProvider } from "@/context/SectionControllerProviders";

import { Flex } from "@chakra-ui/react";

import { Sidebar } from "./components/Sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";
import { SectionContextProvider } from "@/context/SectionContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TThis Is The App Page",
    description: "Generated by create next app",
};

export default function LinksLayout({ children,}: Readonly<{children: React.ReactNode;}>) {

    return (
        
            <section className="dark" id="app">
                <DBContextProvider>
                    <SectionControllerProvider> { /* CRUD OPERATIONS */ }
                        <SectionContextProvider> { /* UI SIDE */ }
                            <Flex flexDir="row" className="no-scrollbar">
                                <Sidebar />
                                <div className="w-full p-0 overflow-hidden !select-none">
                                    {children}
                                </div>
                            </Flex>
                            <Toaster />
                        </SectionContextProvider>
                    </SectionControllerProvider>
                </DBContextProvider>
            </section>
        
    );
}
