import type { Metadata } from "next";

import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import "@/styles/globals.css";

import { DBContextProvider } from "@/context/DBContextProvider";
import { SectionControllerProvider } from "@/context/SectionControllerProviders";

import { Box, Flex } from "@chakra-ui/react";

import { Sidebar } from "./components/Sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";

import { SectionContextProvider } from "@/context/SectionContextProvider";
import { LinkControllerProvider } from "@/context/LinkControllerProviders";
import { SettingContextProvider } from "@/context/SettingContextProvider";
//import { KeyboardNavigationContextProvider } from "@/context/KeyboardNavigationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TThis Is The App Page",
    description: "Generated by create next app",
};

export default function LinksLayout({ children,}: Readonly<{children: React.ReactNode;}>) {

    return (
        <section>
            <DBContextProvider>
                <SectionControllerProvider> { /* CRUD OPERATIONS */ }
                        <LinkControllerProvider> { /* CRUD OPERATIONS */ }
                            <SettingContextProvider> { /* App Settings */ }
                                <Flex flexDir="row" className="no-scrollbar">
                                    <Sidebar />
                                    <Box className="w-full p-0 overflow-hidden !select-none">
                                        {children}
                                    </Box>
                                </Flex>
                                <Toaster />
                            </SettingContextProvider>
                        </LinkControllerProvider>
                </SectionControllerProvider>
            </DBContextProvider>
        </section>
    )
}
