import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GeistSans } from 'geist/font/sans';
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Flex } from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TThis Is The App Page",
    description: "Generated by create next app",
};

export default function LinksLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
    return (
        <html lang="en" className={GeistSans.className}>
            <body className="dark" id="app">
                <Flex flexDir="row">
                    <div>
                        <Sidebar />
                    </div>
                    <div className="w-full p-0">
                        {children}
                    </div>
                </Flex>
                <Toaster />
            </body>
        </html>
    );
}
