
const IMAGEKIT_IO_PUBLIC_KEY = process.env.IMAGEKIT_IO_PUBLIC_KEY as string;
const IMAGEKIT_IO_PRIVATE_KEY = process.env.IMAGEKIT_IO_PRIVATE_KEY as string;

export { IMAGEKIT_IO_PUBLIC_KEY, IMAGEKIT_IO_PRIVATE_KEY };